{
    'name': 'Desality Customization',
    'version': '18.0.1.2.0',
    'category': 'CRM',
    'summary': 'Comprehensive business process automation for referral management, commission tracking, and workflow integration',
    'author': 'ACES Consulting',
    'website': '',
    'depends': [
        'base',
        'base_automation',
        'crm',
        'product',
        'account',
        'portal',
        'website',
        'appointment',
        'project',
        'calendar',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/res_partner_views.xml',
        'views/crm_lead_views.xml',
        'views/product_template_views.xml',
        'views/account_move_views.xml',
        'views/res_users_views.xml',
        'views/project_views.xml',
        'views/project_task_views.xml',
        'views/calendar_event_views.xml',
        'views/appointment_type_views.xml',
        'views/appointment_template.xml',
        'data/base_automation.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',
}