from . import res_partner
from . import crm_lead
from . import product_template
from . import account_move
from . import res_users
from . import calendar_event
from . import project_task
from . import project_project
from . import appointment_type